<?php
return [
    'SHOPIFY_DOMAIN' => env('SHOPIFY_DOMAIN'),
    'SHOPIFY_ACCESS_TOKEN' => env('SHOPIFY_ACCESS_TOKEN'),
    'SHOPIFY_API_KEY' => env('SHOPIFY_API_KEY'),
    'SHOPIFY_API_SECRET' => env('SHOPIFY_API_SECRET'),
    'SHOPIFY_APP_SCOPES' => env('SHOPIFY_APP_SCOPES'),
    'SHOPIFY_APP_HOST_NAME' => env('SHOPIFY_APP_HOST_NAME'),
    'limit_pagination' => 12
];
