name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Pull latest code (optional if checkout done)
      run: cd ~/projects/bike-parts && git pull origin main
    - name: Build
      run: |
        cd ~/projects/bike-parts
        docker compose exec workspace php artisan migrate
        docker compose exec workspace php artisan config:cache
        docker compose exec workspace php artisan route:cache
